/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fivestar_sirius_BoardView */

#ifndef _Included_com_fivestar_sirius_BoardView
#define _Included_com_fivestar_sirius_BoardView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fivestar_sirius_BoardView
 * Method:    legalMoves
 * Signature: (Lcom/fivestar/sirius/Board;I)V
 */
JNIEXPORT void JNICALL Java_com_fivestar_sirius_BoardView_legalMoves
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
