/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fivestar_sirius_BoardLogic */

#ifndef _Included_com_fivestar_sirius_BoardLogic
#define _Included_com_fivestar_sirius_BoardLogic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fivestar_sirius_BoardLogic
 * Method:    doMove
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_fivestar_sirius_BoardLogic_doMove
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
