/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fivestar_sirius_BoardLogic */

#ifndef _Included_com_fivestar_sirius_BoardLogic
#define _Included_com_fivestar_sirius_BoardLogic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fivestar_sirius_BoardLogic
 * Method:    calculateLegal
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_fivestar_sirius_BoardLogic_calculateLegal
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_fivestar_sirius_BoardLogic
 * Method:    calculateFlips
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_fivestar_sirius_BoardLogic_calculateFlips
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
