/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fivestar_sirius_Board */

#ifndef _Included_com_fivestar_sirius_Board
#define _Included_com_fivestar_sirius_Board
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fivestar_sirius_Board
 * Method:    doMove
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_fivestar_sirius_Board_doMove
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
